services:
  tpaperdelivery:
    image: ${DOCKER_REGISTRY-}tpaperdelivery
    build:
      context: TPaperDelivery
      dockerfile: Dockerfile
    env_file:  
      - settings.env 

  tpaperorders:
    image: ${DOCKER_REGISTRY-}tpaperorders
    build:
      context: TPaperOrders
      dockerfile: Dockerfile
    env_file:  
      - settings.env

